name: "Build and cache hc-pilot"
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-cache-hc-pilot:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-11, ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - uses: cachix/cachix-action@v14
        with:
          name: darksoil-studio

      - name: Build and cache hc-pilot
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          nix build --accept-flake-config -L .#hc-pilot
          cachix push darksoil-studio $(nix --accept-flake-config path-info --accept-flake-config .#hc-pilot)
          cachix pin darksoil-studio hc-progenitor $(nix --accept-flake-config path-info --accept-flake-config .#hc-pilot)
